[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
init-if-needed = false

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJsyFbPVwwQQftas5LWNetbgqrgc"

[[test.validator.clone]]
address = "ATokenGPvbdGVqstVQmcLsNZAqeEctnam4C3crfAVrFj"

[programs.localnet]
fairlaunch = "FairLaunchProgramIDWillBeGeneratedHere11111"

[programs.testnet]
fairlaunch = "FairLaunchProgramIDWillBeGeneratedHere11111"

[programs.mainnet]
fairlaunch = "FairLaunchProgramIDWillBeGeneratedHere11111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"